import "./globals.css";
import Footer from "./shared/Footer";

export const metadata = {
  title: "Feast Express",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
