import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-inter ">
        <div>
          <Navbar />
        </div>

        <div className="py-6 h-[calc(100vh-96px)]">{children}</div>
      </body>
    </html>
  );
}
