import Navbar from "@/components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Feast Express",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
