import Navbar from "@/components/shared/Navbar";
import "../globals.css";
import Footer from "@/components/shared/Footer";
import { Suspense } from "react";
import Loading from "@/components/shared/Loading";
export const metadata = {
  title: "Delish -  Your Favorite Flavors, Delivered",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <div className="sticky z-40 top-0 ">
            <Navbar />
          </div>

          {/* don't remove height  */}
          <div className=" font-poppins min-h-[calc(100vh-96px)]  ">
            {children}
          </div>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
