import Navbar from "../../../components/shared/Navbar";
import "../globals.css";
import Footer from "../../../components/shared/Footer";
import AuthProvider from "@/services/AuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Delish -  Your Favorite Flavors, Delivered",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="sticky z-[999] top-0 ">
            <Navbar />
          </div>
          {/* don't remove height  */}
          <div className=" font-Inter min-h-[calc(100vh-80px)] pb-10  ">
            {children}
            <Toaster />
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
