import DashboardNav from "@/components/shared/Dashboard/DashboardNav";
import "../../globals.css";
import TopBar from "@/components/shared/Dashboard/TopBar";

export const metadata = {
  title: "Delish -  Your Favorite Flavors, Delivered",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center h-screen">
          <div className="w-fit  h-full font-Manrope font-bold px-10  py-4">
            <DashboardNav />
          </div>
          <div className="h-screen  flex-1  font-Manrope  overflow-y-auto  ">
            <TopBar />
            <div className="p-10 bg-gray-100">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
